### ISSUE TITLE
Query result is empty on non-empty tables

### ISSUE THREAD

**Issue by wangxiaoying** [duckdblabs/postgres_scanner#12]
I have a postgres instance running in docker with a non-empty `test_table`:
<img width="986" alt="image" src="https://user-images.githubusercontent.com/5569610/193116063-17c4483d-941f-4f17-ae8d-a05c793b07b5.png">

When I select the result directly through `POSTGRES_SCAN` from this table in duckdb, the result is empty:
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/5569610/193116458-a212d0fd-5b55-4152-922b-63f29ac2e9de.png">

When I attach the tables using `POSTGRES_ATTACH`, I can see the table is successfully a attached with correct schema, however the result is still empty:
<img width="1760" alt="image" src="https://user-images.githubusercontent.com/5569610/193117184-22885045-95bc-47b3-b191-c5e6d79af3bd.png">

I'm not sure what's happening here. Is there anything that I missed to configure?

**Comment by Alex-Monahan** [comment]
I apologize if this is a basic question! Did you already commit the transaction where the table was populated?

**Comment by wangxiaoying** [comment]
> I apologize if this is a basic question! Did you already commit the Postgres transaction where the table was populated?

Thanks for the quick reply. Yes, and I can fetch the table from new connections using psql or python client.

**Comment by wangxiaoying** [comment]
It turns out the extension uses [`pages_approx` to check whether the local state is done](https://github.com/duckdblabs/postgres_scanner/blob/main/postgres_scanner.cpp#L772), which is collected from the `pg_class.relpages` and will only an estimation and will be updated by commands like `analyze`.

The result becomes correct after I run `analyze` on postgres. But I wonder is it a good way to use the estimation result to check the result? If it has to be done in this way, would be better to mention it in the readme.

**Comment by hannes** [comment]
Can you try with the latest again? I think this is fixed.

**Comment by wangxiaoying** [comment]
@hannes It works now, thank you!
