### ISSUE TITLE
Decimal out of range error when trying to read a NUMERIC type

### ISSUE THREAD

**Issue by Mytherin** [duckdblabs/postgres_scanner#13]
Create the following Postgres table:

```sql
-- postgres
create table numeric_test(x int, y numeric, z numeric);
insert into numeric_test values (0), (0), (0);
```

Then try to read it with the postgres scanner:
```sql
-- duckdb
SELECT * FROM postgres_scan('', 'public', 'numeric_test');
```

This results in the following internal error:

```
INTERNAL Error: Decimal has a width of 255 which is bigger than the maximum supported width of 38
```

**Comment by hannes** [comment]
So when a column is declared `NUMERIC` its "length" is -1, meaning any value can be present. Not sure what to convert this to in DuckDB. `DOUBLE`? String?

**Comment by Mytherin** [comment]
I assume the scale is not known either? I would say `DOUBLE`. Either that or default to a very large decimal (e.g. `DECIMAL(38,10)` and throw exceptions when values are out of range.

**Comment by jeffling** [comment]
Is there currently a workaround, or are numeric types just not supported?

**Comment by hannes** [comment]
Should be fixed, we now read those as DOUBLE as Mark suggested
