### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by darrenkeydata** [duckdblabs/postgres_scanner#14]
try to connect to a postgres db that requires SSL gives this error 

`sslmode value "require" invalid when SSL support is not compiled in`

**Comment by hannes** [comment]
Indeed SSL is currently not supported

**Comment by justbldwn** [comment]
thanks for the quick response @hannes - are there any plans to support SSL in the future?

**Comment by hannes** [comment]
We will certainly consider adding this, provided libpq' use of SSL is somewhat sane.

**Comment by ttjmartinez** [comment]
+1, most of the databases that I connect to require SSL
