### ISSUE TITLE
IO Error: Unsupported Postgres type _bpchar

### ISSUE THREAD

**Issue by marblestation** [duckdblabs/postgres_scanner#15]
When I try to connect to one specific postgres database (I don't have issues with others), I get the following error:

```
$ ./duckdb
v0.5.1 7c111322d
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D INSTALL postgres_scanner; LOAD postgres_scanner;
D CALL postgres_attach('host=localhost port=5432 dbname=dbname user=user password=pw');
Error: IO Error: Unsupported Postgres type _bpchar
```

The postgres version is `PostgreSQL 12.6 (Ubuntu 12.6-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit`.

I see that the error message is coming from: https://github.com/duckdblabs/postgres_scanner/blob/e3202f2acef75b91905e6595a605eb8ab9bb4849/postgres_scanner.cpp#L198

The database has multiple tables, and I am using these column types:

```
integer
character(19)
character(19)[]
boolean
integer[]
text
text[]
timestamp without time zone
```

Plus a couple of custom enums. Is there any of these types not implemented yet? Or maybe it is related to something else? Any clues? Let me know if you need more info.

**Comment by marblestation** [comment]
I can confirm that this is due to postgres arrays, the problem appears in tables where I have a `text[]` field or a `int[]` field (in that case, the error is `Error: IO Error: Unsupported Postgres type _int4`).

I can retrieve data without issues when I target a specific table that does not have any array field using:

```
SELECT * FROM postgres_scan_pushdown('host=localhost port=15432 dbname=name user=user password=pw connect_timeout=1', 'public', 'table_name') LIMIT 2;
```

For the tables with arrays, I can read them using pandas and then import them into duckdb. But I am expecting this to be less efficient than if we could use `postgres_scanner` directly. It would be great if this could be implemented! 😄

**Comment by edwardw** [comment]
Having the exact same issue rn, although for me it is an array of strings so the error message is slightly different. Postgres version 14.5.

**Comment by hannes** [comment]
This should work now
