### ISSUE TITLE
IO Error: Unsupported Postgres type jsonb

### ISSUE THREAD

**Issue by exyi** [duckdblabs/postgres_scanner#17]
When I try to attach a database which contains `jsonb` columns, the command fails

```
D CALL POSTGRES_ATTACH('');
Error: IO Error: Unsupported Postgres type jsonb
```

I'd appreciate if it was supported. Even if it's not supported, it would be great if only failed when querying the tables which contain 
jsonb.

**Comment by hannes** [comment]
JSONB looks quite involved to parse: https://github.com/postgres/postgres/blob/master/src/backend/utils/adt/jsonb.c

**Comment by hannes** [comment]
Should be fixed
