### ISSUE TITLE
how to attach many schemas？

### ISSUE THREAD

**Issue by wonb168** [duckdblabs/postgres_scanner#18]
call postgres_attach default schema is public，and how to attach many schemas？attach a db，duckdb vs pg can support schema to schema？

**Comment by hannes** [comment]
You can call attach multiple times with different schema[ta]?

**Comment by alitrack** [comment]
> You can call attach multiple times with different schema[ta]?

If  different postgres has same table name,how to do?

How about add different duckdb schema support, parameters not only has source_schema, but also dest_schema

**Comment by wonb168** [comment]
and one sql may join tables in different schemas, eg. 
select * from biz.table1 join edw.table2,then how use postgre scanner to write this sql
?

**Comment by alitrack** [comment]
have a look https://github.com/alitrack/postgres_scanner/tree/sink_schema

I tried PR, but automatic workflow was cancelled, I have no idea what's matter.

### sink_schema usage

attach Postgres schema to another DuckDB schema.

```sql
-- create a new schema in DuckDB first
create schema abc;
CALL postgres_attach('dbname=postgres user=postgres host=127.0.0.1',source_schema='public' , sink_schema='abc');
select table_schema,table_name,table_type  FROM information_schema.tables;
```

**Comment by wonb168** [comment]
done
