### ISSUE TITLE
Selection not being pushed down by 'postgres_scan_pushdown'

### ISSUE THREAD

**Issue by marblestation** [duckdblabs/postgres_scanner#19]
It looks like the `postgres_scan_pushdown` is not behaving as intended or more documentation is needed. I am running the following query:

```
SELECT *
FROM postgres_scan_pushdown('host=localhost port=5432 dbname=name user=user password=pw connect_timeout=1', 'public', 'entries')
WHERE id in (15078724, 14345981, 7502816, 19982348, 19955057, 5595804, 3090984, 15114757, 4342971, 3684533, 15332157, 7977537, 6968341, 3565833, 13419215, 7214809, 4768957, 11041866, 15094037, 3195645, 3630081, 3748183, 3836289, 3895904, 4069128, 4235944, 4368211, 4514836, 4734324, 17768845, 6413051, 6568003, 6681069, 3338266, 334
5805, 1696061, 3382514, 6942962, 7316728, 3659078);
```

It takes exactly the same amount of time (~16 seconds) that the same query without the `WHERE` clause, or the same query with the `WHERE` clause but with `postgres_scan` instead of `postgres_scan_pushdown`. It looks like if the `postgres_scan_pushdown` is not actually pushing down the filters (i.e., they are not run by postgres) and it is getting the full table and then filtering locally.

However, the following query seems to work as expected:

```
SELECT *
FROM postgres_scan_pushdown('host=localhost port=5432 dbname=name user=user password=pw connect_timeout=1', 'public', 'entries')
WHERE id in (15078724);
```

It returns the results very quickly (below a second). While it is slower (~16 seconds), as expected, if I use the pushdown version:

```
SELECT *
FROM postgres_scan('host=localhost port=5432 dbname=name user=user password=pw connect_timeout=1', 'public', 'entries')
WHERE id in (15078724);
```

Hence, it seems that the pushdown function only works with certain (very simple?) conditions. I am using `duckdb v0.5.1 7c111322d`. Is this a bug or is it an undocumented limitation?

**Comment by Mytherin** [comment]
The pushdown on filters is limited to the filters that DuckDB itself knows how to push down, which are currently limited to combinations of simple comparisons.`IN` clauses with a single row are rewritten to an equality expression which is why they can be pushed down.

The pushdown will automatically be extended as DuckDB is extended to push down more operations. See `duckdb/duckdb#4295` for a related issue.

**Comment by marblestation** [comment]
Ok, understood! I see that `id = 1 OR id = 2` is also not pushed down. We'll have to wait for DuckDB to extend the push down operations. Thanks!
