### ISSUE TITLE
unsupported type uuid

### ISSUE THREAD

**Issue by lepfhty** [duckdblabs/postgres_scanner#25]
duckdb version: `v0.5.1 7c111322d`

To reproduce:
```sql
-- in postgres
CREATE TABLE example (
  id uuid
);
```

```
-- in duckdb
D install postgres_scanner;
D load postgres_scanner;
D select * from postgres_scan('dbname=db', 'public', 'example') limit 10;
Error: Invalid Error: IO Error: Unsupported Postgres type uuid
```

I have a [patch](https://github.com/lepfhty/postgres_scanner/commit/b43c027893e00f9a47ab81ae665e5da0fb89acfe) that seems to be working. I updated a test and got `make test` to pass locally (with some changes to the build/test scripts that are not included in the patch). 

Love what you guys are doing. I can open a pull request if you'd like.

**Comment by Mause** [comment]
@lepfhty a pull request would be great, thanks!
