### ISSUE TITLE
scanner is powerful, but lack of some features

### ISSUE THREAD

**Issue by wonb168** [duckdblabs/postgres_scanner#28]
postgres_scanner can read greenplum table directly, but lack of some features:
1. only support 1 schema, but sql may join different schemas tables, eg. ` select * from sch1.table1 join sch2.table2 on ...`
2. not support uuid、array、json/jsonb columns
3. not support nemeric if not have length 
sample data:
```
create table test_scanner(id uuid,code text,sizes int[],skc jsonb,number numeric)
;
insert into test_scanner values(gen_random_uuid(),'test', array[1,2,3],'{"a":1,"b":2}'::jsonb,1234.5000);
```
we use greenplum as HTAP, and night is busy time, but greenplum not support expand temporary，
if postgres_scanner is fully functional, the separation of memory and calculation can be realized，
and duckdb will be a very powerful tool, just like a spark for hive, and **Duckdb+Greenplum will be surpass Spark+Hive** in many situations.

**Comment by hannes** [comment]
all the types you mentioned should be supported now. Regarding the schema, valid point. Of course you can workaround by re-creating the schemas in duckdb and attaching there specifically.
