### ISSUE TITLE
How to specify the "filter_pushdown" parameters for each table?

### ISSUE THREAD

**Issue by SingleLyra** [duckdblabs/postgres_scanner#36]
Hi! 
First of all : Duckdb is really great!
I'm trying to specify the `filter_pushdown` parameters by using `postgres_scan_pushdown` function for each table, however, it seems that it can only be used once in a query.
I got this exception: "duckdb.BinderException: Binder Error: **Duplicate alias "postgres_scan_pushdown"** in query!"
Here is my query:
```
SELECT l_orderkey, SUM(l_extendedprice*(1.0-l_discount)) as revenue, o_orderdate, o_shippriority 
FROM postgres_scan_pushdown('host=localhost user=xxx dbname=tpch_sf1 port=xxx','public','customer'), postgres_scan_pushdown('host=localhost user=xxx dbname=tpch_sf1 port=xxx','public','orders'), 
lineitem 
WHERE c_mktsegment = 'BUILDING' AND c_custkey = o_custkey AND l_orderkey = o_orderkey AND o_orderdate < '1995-03-15' AND l_shipdate > '1995-03-15' GROUP BY l_orderkey, o_orderdate, o_shippriority ORDER BY revenue DESC, o_orderdate LIMIT 10;
```
I wonder what can I do to specify `filter_pushdown` the parameter for each table.
Thanks~

**Comment by Alex-Monahan** [comment]
Hello!
You likely need to give a different alias to each scan function:
```sql
SELECT l_orderkey, SUM(l_extendedprice*(1.0-l_discount)) as revenue, o_orderdate, o_shippriority 
FROM postgres_scan_pushdown('host=localhost user=xxx dbname=tpch_sf1 port=xxx','public','customer') alias1, postgres_scan_pushdown('host=localhost user=xxx dbname=tpch_sf1 port=xxx','public','orders') alias2, 
lineitem 
WHERE c_mktsegment = 'BUILDING' AND c_custkey = o_custkey AND l_orderkey = o_orderkey AND o_orderdate < '1995-03-15' AND l_shipdate > '1995-03-15' GROUP BY l_orderkey, o_orderdate, o_shippriority ORDER BY revenue DESC, o_orderdate LIMIT 10;
```

**Comment by SingleLyra** [comment]
> Hello! You likely need to give a different alias to each scan function:
> 
> ```sql
> SELECT l_orderkey, SUM(l_extendedprice*(1.0-l_discount)) as revenue, o_orderdate, o_shippriority 
> FROM postgres_scan_pushdown('host=localhost user=xxx dbname=tpch_sf1 port=xxx','public','customer') alias1, postgres_scan_pushdown('host=localhost user=xxx dbname=tpch_sf1 port=xxx','public','orders') alias2, 
> lineitem 
> WHERE c_mktsegment = 'BUILDING' AND c_custkey = o_custkey AND l_orderkey = o_orderkey AND o_orderdate < '1995-03-15' AND l_shipdate > '1995-03-15' GROUP BY l_orderkey, o_orderdate, o_shippriority ORDER BY revenue DESC, o_orderdate LIMIT 10;
> ```

It works! Thank you so much! ^__^
