### ISSUE TITLE
DuckDB postgres scanner connecting to clickhouse

### ISSUE THREAD

**Issue by alanpaulkwan** [duckdblabs/postgres_scanner#37]
Can it support Clickhouse (which supports psql)?

CALL postgres_attach('postgresql://default:password#@ipaddress:9005/default')

I am happy to share some connection details if anyone is interested. In any case the response was very Clickhouse specific, per below. If I had to guess, DuckDB probes information_schema that Clickhouse in some peculiar way is not compatible with. 

Any hope of debugging?

DB::Exception: Cannot convert string BASE TABLE to type UInt8: while executing 'FUNCTION equals(multiIf(is_temporary, 4, like(engine, '%View'), 2, like(engine, 'System%'), 5, equals(has_own_data, 0), 3, 1) : 19, 'BASE TABLE' : 13) -> equals(multiIf(is_temporary, 4, like(engine, '%View'), 2, like(engine, 'System%'), 5, equals(has_own_data, 0), 3, 1), 'BASE TABLE') UInt8 : 20'
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
 ERROR:  Query execution failed.
DB::Exception: Cannot convert string BASE TABLE to type UInt8: while executing 'FUNCTION equals(multiIf(is_temporary, 4, like(engine, '%View'), 2, like(engine, 'System%'), 5, equals(has_own_data, 0), 3, 1) : 19, 'BASE TABLE' : 13) -> equals(multiIf(is_temporary, 4, like(engine, '%View'), 2, like(engine, 'System%'), 5, equals(has_own_data, 0), 3, 1), 'BASE TABLE') UInt8 : 20'
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

**Comment by hannes** [comment]
Not sure what's going on there, but for now we depend on some postgres internals like the TID scan, I doubt ClickHouse has this too. Going forward, we may consider adding a single-threaded scan for anything that does not look like a Postgres base table (e.g. views)
