### ISSUE TITLE
supporting MySQL

### ISSUE THREAD

**Issue by alanpaulkwan** [duckdblabs/postgres_scanner#38]
This is the killer feature I've been waiting for. Generally, though, am hoping that it supports databases that support a given interface (psql is supported by QuestDB and Clickhouse, for example).

It would also be great to see some support for MySQL. The rationale would be: MySQL is as prevalent as Postgres, if not more. Moreover, emergent databases (Clickhouse, Starrocks, Doris, etc) tend to have mysql compatibility. Thus one could possibly grab MySQL data + the data of all the other databases via this protocol.

**Comment by hannes** [comment]
We might eventually add MySQL support, but there is no timeline on this (yet).
