### ISSUE TITLE
postgres_scanner.duckdb_extension: undefined symbol: _ZN6duckdb28SimpleNamedParameterFunction8ToStringEv

### ISSUE THREAD

**Issue by wonb168** [duckdblabs/postgres_scanner#44]
I use `BUILD_PYTHON=1 make debug` to build the python duckdb, and can import it in python:
```
import duckdb as dd
dd.__version__
'0.5.2-dev1249'
```
but, when I load the postgres_scanner, 
```
con = dd.connect(":memory:", config={"allow_unsigned_extensions": True})
url_pgscan="/root/postgres_scanner/build/debug/extension/postgres_scanner/postgres_scanner.duckdb_extension"
con.install_extension(url_pgscan, force_install=True)
con.load_extension("postgres_scanner")
```
raise error:
```
duckdb.IOException: IO Error: Extension "/root/.duckdb/extensions/550e8ef/linux_amd64_gcc4/postgres_scanner.duckdb_extension" could not be loaded: /root/.duckdb/extensions/550e8ef/linux_amd64_gcc4/postgres_scanner.duckdb_extension: undefined symbol: _ZN6duckdb28SimpleNamedParameterFunction8ToStringEv
```
why?
thanks!

**Comment by Mause** [comment]
Are you building with `EXTENSION_STATIC_BUILD=1 make debug`? This is required on linux for now

**Comment by wonb168** [comment]
> Are you building with `EXTENSION_STATIC_BUILD=1`? This is required on linux for now

not with it，but I confused，I compiled success in Ubuntu this morning，and error in centos7 this afternoon。

**Comment by Mause** [comment]
Compilation can succeed without the flag, but you'll need it if you want to avoid the undefined symbol error

**Comment by wonb168** [comment]
> Compilation can succeed without the flag, but you'll need it if you want to avoid the undefined symbol error
ubuntu success load extension, not with with `EXTENSION_STATIC_BUILD=1`, but centos with `with EXTENSION_STATIC_BUILD=1` also the same error
![image](https://user-images.githubusercontent.com/25274931/198815577-8bcdc358-7bef-4ce3-af98-963e43049d68.png)

**Comment by Mause** [comment]
> > Compilation can succeed without the flag, but you'll need it if you want to avoid the undefined symbol error
> ubuntu success load extension, not with with `EXTENSION_STATIC_BUILD=1`, but centos with `with EXTENSION_STATIC_BUILD=1` also the same error
> ![image](https://user-images.githubusercontent.com/25274931/198815577-8bcdc358-7bef-4ce3-af98-963e43049d68.png)
> 
> **but now in centos7:**
> ![image](https://user-images.githubusercontent.com/25274931/198816048-bb9f4c20-7ec0-4e5c-b157-e71903201db5.png)
> ![image](https://user-images.githubusercontent.com/25274931/198816138-7d93626f-c22f-4eeb-9141-65fe416b2cec.png)
> 
> 

Can you provide a reproduction? Ideally as a Dockerfile or similar

**Comment by wonb168** [comment]
> > > Compilation can succeed without the flag, but you'll need it if you want to avoid the undefined symbol error
> > ubuntu success load extension, not with with `EXTENSION_STATIC_BUILD=1`, but centos with `with EXTENSION_STATIC_BUILD=1` also the same error
> > ![image](https://user-images.githubusercontent.com/25274931/198815577-8bcdc358-7bef-4ce3-af98-963e43049d68.png)
> > 
> > **but now in centos7:**
> > ![image](https://user-images.githubusercontent.com/25274931/198816048-bb9f4c20-7ec0-4e5c-b157-e71903201db5.png)
> > ![image](https://user-images.githubusercontent.com/25274931/198816138-7d93626f-c22f-4eeb-9141-65fe416b2cec.png)
> > 
> > 
> 
> Can you provide a reproduction? Ideally as a Dockerfile or similar

In my centos7 server and docker both error.
docker pull centos:7.4.1708

**Comment by Mause** [comment]
That isn't really enough information to reproduce it. Just to clarify, are you trying to load an extension you compiled yourself with a copy of the duckdb python bindings from PyPI?

**Comment by wonb168** [comment]
> That isn't really enough information to reproduce it. Just to clarify, are you trying to load an extension you compiled yourself with a copy of the duckdb python bindings from PyPI?

my OS：docker pull centos:7.4.1708
my code：git clone -b viking https://github.com/wonb168/postgres_scanner
and compiled：
BUILD_PYTHON=1 make debug
#BUILD_PYTHON=1 EXTENSION_STATIC_BUILD=1 make debug
cd duckdb/tools/pythonpkg
python3 setup.py install

**Comment by hannes** [comment]
The loading is clearly working here. #47 is closed because you modified the source code.
