### ISSUE TITLE
Postgres Scanner support of Table Dee/Dum

### ISSUE THREAD

**Issue by benjiman** [duckdblabs/postgres_scanner#65]
In postgres

`foo=# create database deedum;
CREATE DATABASE
foo=# \c deedum
psql (15rc2, server 14.5)
You are now connected to database "deedum" as user "benji".
deedum=# CREATE TABLE dum();
CREATE TABLE
deedum=# CREATE TABLE dee();
CREATE TABLE
deedum=# INSERT INTO dee DEFAULT VALUES;
INSERT 0 1
`

In duckdb
`D install postgres_scanner;
D load postgres_scanner;
D call postgres_attach('dbname=deedum');
Error: INTERNAL Error: INTERNAL Error: Failed to bind "postgres_scan": Table function must return at least one column`

Expected: Database to attach and tables dee and dum to be queryable.

I was trying to work around duckdb not allowing creation of table [dee/dum](https://wiki.c2.com/?TableDum) natively by connecting to a postgres database containing table dee/dum.

**Comment by hannes** [comment]
Interesting way to work around this
