### ISSUE TITLE
support passing a custom port

### ISSUE THREAD

**Issue by dbist** [duckdblabs/postgres_scanner#87]
### What happens?

it'd be great to pass a custom port to the extension, i.e. `CALL postgres_attach('dbname=defaultdb user=root host=127.0.0.1', port=26257, source_schema='public');`

Today, I get the following

```sql
Error: Binder Error: Invalid named parameter "port" for function postgres_attach
Candidates:     suffix VARCHAR
    sink_schema VARCHAR
    source_schema VARCHAR
    filter_pushdown BOOLEAN
    overwrite BOOLEAN
```

### To Reproduce

simply add `port=portnum` to the attach command

### OS:

OSX 13.2

### PostgreSQL Version:

13.0

### DuckDB Version:

7

### DuckDB Client:

CLI

### Full Name:

Artem Ervits

### Affiliation:

e.g. Cockroach Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
I believe the port can be [part of the connection string](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING):

```sql
CALL postgres_attach('dbname=defaultdb user=root host=127.0.0.1 port=26257', source_schema='public');
```

**Comment by dbist** [comment]
yes thank you @Mytherin, I confirmed and it works when you place the port inside the single quotes as you indicated. My mistake for not seeing the quotes.
